### ISSUE TITLE
Still Don't support latest version (0.12.0-dev.1372+8457439a8) of zig 

### ISSUE THREAD

**Issue by TwinIsland** [Tesseract22/blog-backend#2]
[tianyih5@gelib-4c-43 blog-backend]$ zig build
Fetch Packages [4/3] facil.io... /home/tianyih5/Desktop/project/blog-backend/build.zig.zon:12:20: error: package contains 'zigmod.lock' which has illegal file type 'unknown'
            .url = "https://github.com/vrischmann/zig-sqlite/archive/19535aab5760eeaf2979a9dadfca3bb21d1594b9.tar.gz",
                   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/tianyih5/.cache/zig/p/1220ddb3cf7691c7c5312c89909cd9e53dee6adbc0e6438246e25e888a898923fffe/build.zig.zon:7:20: error: package contains 'lib/facil/fiobj/fiobj_numbers.c' which has illegal file type 'unknown'
            .url = "https://github.com/edyu/facil.io/archive/refs/tags/v0.0.13.tar.gz",
                   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[tianyih5@gelib

**Comment by Tesseract22** [comment]
I was not able to reproduce this on my machine. Consider doing 
```bash
rm -r ~/.cache/zig/
```
 and in `blog-backend` 
```bash
rm -r zig-cache
```
to completely remove `zig build`'s cache and get a fresh build.
